apiVersion: v1
kind: Service
metadata:
  labels:
    app: pw-reactjs-base
  name: pw-reactjs-base
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: pw-reactjs-base
